name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run prod

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml